"use client";
import { useMemo, useState } from "react";

type Rubric={text:string;points:number}; type Demo={title:string;task:string;input:string;output:string;rubric:Rubric[]};
type Benchmark={id:string;name:string;year:string;scope:string;summary:string;tasks:string[];expert:string;rubric:string;access:string;paper:string;data:string;demo:Demo};
type FinSearchRow={prompt_id:string;prompt:string;response_reference?:string|null;judge_prompt_template?:string|null;judge_system_prompt?:string|null;label:string;[key:string]:unknown};

const groups=["全部","金融研究","文档问答","数值推理","工作成果","交互智能体","多模态","表格工作流","桌面操作","安全合规"];
const matrixTasks=["文档问答","数值推理","金融研究","工作成果","工具调用","多轮交互","多模态","表格工作流","桌面操作","安全合规"];

export default function Explorer({benchmarks,finsearchRaw}:{benchmarks:Benchmark[];finsearchRaw:FinSearchRow[]}){
 const [group,setGroup]=useState("全部"); const [query,setQuery]=useState(""); const [selected,setSelected]=useState(benchmarks[0].id);
 const [finRegion,setFinRegion]=useState("Greater China"); const [finTier,setFinTier]=useState("T1"); const [finIndex,setFinIndex]=useState(0);
 const [sightTab,setSightTab]=useState("dataset");
 const filtered=useMemo(()=>benchmarks.filter(b=>(group==="全部"||b.tasks.includes(group))&&(b.name+b.summary+b.tasks.join("")).toLowerCase().includes(query.toLowerCase())),[benchmarks,group,query]);
 const active=benchmarks.find(b=>b.id===selected) || benchmarks[0];
 const finRows=useMemo(()=>finsearchRaw.filter(r=>r.label.includes(`(${finRegion})`)&&r.prompt_id.startsWith(`(${finTier})`)),[finsearchRaw,finRegion,finTier]);
 const finRow=finRows[Math.min(finIndex,Math.max(0,finRows.length-1))];
 const setFinFilter=(kind:"region"|"tier",value:string)=>{if(kind==="region")setFinRegion(value);else setFinTier(value);setFinIndex(0)};
 return <main className="shell">
  <nav className="nav"><div className="brand">FinEval <i>Atlas</i></div><div className="navlinks"><a href="/general">通用 Agent Bench</a><a href="#landscape">数据集</a><a href="#tasks">任务图谱</a><a href="#demo">Demo</a><a className="github" href="https://github.com/yuedai-pbc/FinEval-Atlas" target="_blank" rel="noreferrer">Repository ↗</a></div></nav>
  <header className="hero"><div><span className="eyebrow">Financial Evaluation Intelligence · v0.1</span><h1>把金融评测集<br/>拆到<span className="highlight">可执行</span>的颗粒度</h1><p className="lede">不止收集论文。我们把任务、样例、专家流程与评分规则放在同一张图谱里，帮助研究者快速回答：测什么、怎么构造、谁来判断，以及一条数据究竟如何得分。</p></div><aside className="heroAside"><strong>{benchmarks.length}</strong><p>个代表性评测框架<br/>首批结构化梳理</p><strong>{new Set(benchmarks.flatMap(b=>b.tasks)).size}</strong><p>类任务能力<br/>从问答到真实工作成果</p></aside></header>
  <section className="section"><div className="sectionHead"><div><span className="kicker">DESIGN BLUEPRINT</span><h2>一条高质量样例如何诞生</h2></div><p>专家不是最终“打个分”才出现，而是贯穿任务定义、金标制作、rubric 编写、盲评与争议仲裁。</p></div><div className="pipeline">{[["01","任务采样","从真实金融工作流与岗位成果物反推能力"],["02","专家撰写","从业者提供提示、上下文、附件与参考答案"],["03","交叉审核","另一位专家检查真实性、可解性与歧义"],["04","Rubric 原子化","把正确性拆成可独立验证、带权重的评分点"],["05","盲评校准","人类盲评 + judge 校准，记录分歧与置信度"]].map(x=><div className="stage" key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
  <section id="landscape" className="section"><div className="sectionHead"><div><span className="kicker">BENCHMARK LANDSCAPE</span><h2>代表性数据集</h2></div><p>“开放”区分公开完整集与公开子集；所有 Demo 均为结构示意或基于公开字段的节选，不替代原始数据许可。</p></div><div className="controls">{groups.map(g=><button key={g} className={`chip ${group===g?"active":""}`} onClick={()=>setGroup(g)}>{g}</button>)}<input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索数据集 / 任务..." aria-label="搜索"/></div><div className="cards">{filtered.length?filtered.map(b=><article className="card" key={b.id}><div className="cardTop"><span className="eyebrow">{b.year} · {b.scope}</span><span className={`status ${b.access.includes("子集")?"partial":""}`}>{b.access}</span></div><h3>{b.name}</h3><p className="summary">{b.summary}</p><div className="tags">{b.tasks.map(t=><span className="tag" key={t}>{t}</span>)}</div><div className="facts"><div><small>专家参与</small><b>{b.expert}</b></div><div><small>评分方式</small><b>{b.rubric}</b></div></div><div className="links"><a href={b.paper} target="_blank">论文 / 说明 ↗</a><a href={b.data} target="_blank">公开数据 ↗</a><a href="#demo" onClick={()=>setSelected(b.id)}>查看 Demo ↓</a></div></article>):<div className="empty">没有匹配结果，试试更宽泛的关键词。</div>}</div></section>
  <section id="tasks" className="section"><div className="sectionHead"><div><span className="kicker">TASK COVERAGE</span><h2>任务覆盖矩阵</h2></div><p>圆点表示核心任务，珊瑚色表示间接覆盖。它揭示传统问答集与真实工作流评测之间的断层。</p></div><div className="matrixWrap"><table className="matrix"><thead><tr><th>评测集</th>{matrixTasks.map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{benchmarks.map(b=><tr key={b.id}><td>{b.name}</td>{matrixTasks.map(t=><td key={t}>{b.tasks.includes(t)?<span className="dot"/>:(t==="安全合规"&&b.tasks.includes("交互智能体"))?<span className="dot half"/>:<span className="dash">—</span>}</td>)}</tr>)}</tbody></table></div></section>
  <section id="finsearch-raw" className="section"><div className="sectionHead"><div><span className="kicker">OFFICIAL DATASET · UNEDITED</span><h2>FinSearchComp 原始测试集 Demo</h2></div><p>以下 {finsearchRaw.length} 条记录从官方 635 条 CC BY 4.0 数据文件按地区与 T1/T2/T3 分层抽取。问题、标准答案、标签和 judge prompt 均未翻译、改写或总结；完整原始文件可通过链接核验。</p></div>
   <div className="sourceRail"><a href="https://proceedings.iclr.cc/paper_files/paper/2026/hash/4d42358702dff82e1436550a05ade260-Abstract-Conference.html" target="_blank">ICLR 2026 论文 ↗</a><a href="https://arxiv.org/abs/2509.13160" target="_blank">arXiv ↗</a><a href="https://randomtutu.github.io/FinSearchComp/" target="_blank">项目主页 ↗</a><a href="https://github.com/randomtutu/FinSearchComp" target="_blank">官方 GitHub ↗</a><a href="https://huggingface.co/datasets/ByteSeedXpert/FinSearchComp" target="_blank">Hugging Face ↗</a><a href="https://huggingface.co/datasets/ByteSeedXpert/FinSearchComp/blob/main/finsearchcomp_data.json" target="_blank">原始 JSON ↗</a><a href="https://github.com/randomtutu/FinSearchComp/tree/main/finsearchcomp/eval" target="_blank">评测代码 ↗</a></div>
   <div className="finSummary"><div><strong>635</strong><span>原始问题</span></div><div><strong>2</strong><span>区域子集</span></div><div><strong>3</strong><span>任务层级</span></div><div><strong>70</strong><span>金融专家</span></div></div>
   <div className="coverageGrid"><div className="coverageTitle">原始记录分布</div>{[["Greater China","T1",110],["Greater China","T2",100],["Greater China","T3",88],["Global","T1",134],["Global","T2",119],["Global","T3",84]].map(([r,t,n])=><button key={`${r}${t}`} className={`coverageCell ${finRegion===r&&finTier===t?"active":""}`} onClick={()=>{setFinRegion(String(r));setFinTier(String(t));setFinIndex(0)}}><span>{r}</span><b>{t}</b><i style={{width:`${Number(n)/1.34}%`}}/><em>{n} 条</em></button>)}</div>
   <div className="rawExplorer"><aside className="rawFilters"><label>区域 / Market</label>{["Greater China","Global"].map(r=><button key={r} className={finRegion===r?"active":""} onClick={()=>setFinFilter("region",r)}>{r}<small>{r==="Greater China"?"大中华市场":"全球市场"}</small></button>)}<label>任务 / Task</label>{[["T1","Time-Sensitive Data Fetching"],["T2","Simple Historical Lookup"],["T3","Complex Historical Investigation"]].map(([t,n])=><button key={t} className={finTier===t?"active":""} onClick={()=>setFinFilter("tier",t)}>{t}<small>{n}</small></button>)}</aside>
    <div className="rawRecord">{finRow&&<><div className="recordNav"><div><span>OFFICIAL RECORD</span><b>{finRow.prompt_id}</b></div><div className="pager"><button disabled={finIndex===0} onClick={()=>setFinIndex(i=>i-1)}>←</button><span>{finIndex+1} / {finRows.length}</span><button disabled={finIndex===finRows.length-1} onClick={()=>setFinIndex(i=>i+1)}>→</button></div></div><div className="rawField primary"><label>prompt</label><p>{finRow.prompt}</p></div><div className="rawField answer"><label>response_reference</label><p>{finRow.response_reference || <i>官方记录为空：T1 由实时 API / ground truth 规则动态验证</i>}</p></div><div className="rawField"><label>label</label><p>{finRow.label}</p></div><details className="rawDetails"><summary>展开官方 Judge 字段与全部原始字段</summary><div className="rawField"><label>judge_prompt_template</label><pre>{finRow.judge_prompt_template || "null"}</pre></div><div className="rawField"><label>judge_system_prompt</label><pre>{finRow.judge_system_prompt || "null"}</pre></div><div className="rawField"><label>raw JSON object</label><pre>{JSON.stringify(finRow,null,2)}</pre></div></details></>}</div>
   </div><p className="provenance">来源版本：randomtutu/FinSearchComp main · data/finsearchcomp_data.json · SHA ff89538172a93e10e85f04ca666bbf5adba2df6d · Demo 按 2 个地区 × 3 类任务分层抽样；页面仅改变排版，不改变字段内容。</p>
  </section>
  <section id="finsight-audit" className="section"><div className="sectionHead"><div><span className="kicker">PAPER × CODE AUDIT</span><h2>FinSight：评测集与开源代码</h2></div><p>名称核对：未检索到对应的 “FirmSight” 金融论文；此处分析前述 ACL 2026 FinSight。论文声称的 benchmark 与仓库实际开放内容分开展示。</p></div>
   <div className="sourceRail"><a href="https://aclanthology.org/2026.acl-long.265/" target="_blank">ACL Anthology ↗</a><a href="https://aclanthology.org/2026.acl-long.265.pdf" target="_blank">正式 PDF ↗</a><a href="https://arxiv.org/abs/2510.16844" target="_blank">arXiv ↗</a><a href="https://github.com/RUC-NLPIR/FinSight" target="_blank">官方 GitHub ↗</a><a href="https://github.com/RUC-NLPIR/FinSight/blob/main/README.md" target="_blank">README ↗</a><a href="https://github.com/RUC-NLPIR/FinSight/tree/main/assets/example_reports" target="_blank">生成报告样例 ↗</a><a href="https://github.com/RUC-NLPIR/FinSight/blob/main/my_config.yaml" target="_blank">官方配置实例 ↗</a><a href="https://github.com/RUC-NLPIR/FinSight/tree/main/src/agents" target="_blank">Agent 源码 ↗</a><a href="https://github.com/RUC-NLPIR/FinSight/tree/main/src/tools" target="_blank">工具库 ↗</a></div>
   <div className="auditAlert"><b>开放性结论</b><span>生成系统代码：已开放</span><span>20 个评测目标清单：未在仓库找到</span><span>券商金标报告：未在仓库找到</span><span>论文评测脚本：未在仓库找到</span></div>
   <div className="sightTabs">{[["dataset","01 评测集"],["metrics","02 指标与专家"],["code","03 代码审计"],["original","04 官方原始实例"]].map(([id,n])=><button key={id} className={sightTab===id?"active":""} onClick={()=>setSightTab(id)}>{n}</button>)}</div>
   <div className="sightPanel">{sightTab==="dataset"&&<><div className="sightHero"><div><strong>20</strong><span>评测目标</span></div><div><strong>10</strong><span>公司级</span></div><div><strong>10</strong><span>行业级</span></div><div><strong>&gt;20</strong><span>金标报告页数门槛</span></div><div><strong>&gt;20</strong><span>图表数量门槛</span></div></div><div className="twoCols"><div className="infoBlock"><span className="blockNo">A</span><h3>Company-level</h3><p>论文描述：从权威金融平台选择不同市场、行业与市值的公司；覆盖 A 股、港股等。每个目标配一份专业券商深度报告作为 golden reference。</p><b>公开状态</b><p className="warning">完整 10 家公司名单和对应金标报告目前未在官方仓库发布。论文附录只展示商汤科技案例。</p></div><div className="infoBlock"><span className="blockNo">B</span><h3>Industry-level</h3><p>论文描述：选择金融平台上的高关注行业作为研究目标，使用专业机构行业报告作为 golden reference。</p><b>公开状态</b><p className="warning">完整 10 个行业名单和对应金标报告目前未在官方仓库发布。仓库公开了“金融 AI Agent 发展”生成报告样例。</p></div></div><div className="flowline"><span>Research target</span><i>→</i><span>专业券商金标报告</span><i>→</i><span>模型生成长报告</span><i>→</i><span>9 项 0–10 分评价</span></div></>}
    {sightTab==="metrics"&&<><div className="metricGrid">{[["Factual Accuracy","Core Conclusion Consistency","Textual Faithfulness","Text–Image Coherence"],["Information Effectiveness","Information Richness","Coverage","Analytical Insight"],["Presentation Quality","Structural Logic","Language Professionalism","Chart Expressiveness"]].map((m,i)=><div className="metricGroup" key={m[0]}><span>0{i+1}</span><h3>{m[0]}</h3>{m.slice(1).map(x=><p key={x}>{x}</p>)}</div>)}</div><div className="judgeGrid"><div><b>自动评价</b><p>Gemini-2.5-Pro 为主 judge；每个样例独立运行 3 次并报告 95% 置信区间；GPT-5 作为辅助 judge 检查跨模型一致性。</p></div><div><b>人工评价</b><p>6 名具有金融背景的研究生，对 FinSight、Gemini-2.5-Pro Deep Research 和 OpenAI Deep Research 进行比较；报告 Krippendorff’s α 与 Pearson’s r。</p></div><div><b>补充指标</b><p>关键金融事实召回：FinSight 平均命中 7.1/13，召回率 54.6%；另分析引用来源权威性分布。</p></div></div><div className="scoreTable"><div className="scoreHead"><span>系统</span><span>Fact.</span><span>Analytical</span><span>Presentation</span><span>Avg.</span></div>{[["FinSight","7.40*","8.48*","8.05*","8.09"],["Gemini-2.5-Pro DR","6.18*","7.68*","6.58*","6.82"],["OpenAI DR","5.98*","6.22*","6.80*","6.11"]].map(r=><div className="scoreRow" key={r[0]}>{r.map((x,i)=><span key={i}>{x}</span>)}</div>)}</div><p className="provenance">* 三个维度值为论文表格中各自 3 个子指标的页面展示性均值；正式比较应以论文九项原始分数为准。</p></>}
    {sightTab==="code"&&<><div className="codeMatrix">{[["多 Agent 主流程","已开放","src/agents"],["金融与宏观工具库","已开放","src/tools"],["CAVM / Memory","已开放","src/memory"],["Prompt 模板","已开放","src/agents/*/prompts"],["Web UI","已开放","demo/frontend + backend"],["生成报告样例","部分开放","assets/example_reports"],["20 项 benchmark 输入","未开放","仓库未发现"],["券商 golden reports","未开放","仓库未发现"],["论文 9 指标评测代码","未开放","仓库未发现"]].map(r=><div className="codeRow" key={r[0]}><b>{r[0]}</b><span className={r[1]==="未开放"?"closed":r[1]==="部分开放"?"partial":"open"}>{r[1]}</span><code>{r[2]}</code></div>)}</div><div className="architectureStrip">{["Data Collector","Deep Search Agent","Data Analyzer + VLM","Report Generator","DOCX / PDF"].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b></div>)}</div><p className="auditNote">代码许可证以仓库当前 LICENSE/README 为准（当前 README 标示 GPL v3）。运行需要 LLM、VLM、Embedding 与可选搜索 API；因此“代码开放”不等于论文结果可零成本复现。</p></>}
    {sightTab==="original"&&<><div className="originalHead"><div><span>OFFICIAL FILE</span><b>my_config.yaml</b></div><a href="https://github.com/RUC-NLPIR/FinSight/blob/main/my_config.yaml" target="_blank">在 GitHub 对照 ↗</a></div><div className="configColumns"><div><h3>原始研究目标</h3><pre>{`target_name: "商汤科技"\nstock_code: "00020.hk"\ntarget_type: 'financial_company'\noutput_dir: "./outputs/exp-v3"\nlanguage: 'zh'`}</pre><h3>原始数据采集任务</h3><pre>{`- 资产负债表, 利润表, 现金流量表三大财务报表\n- 股票基本信息以及股价数据\n- 股东结构\n- 投资评级\n- 公司市销率, 净资产收益率(ROE), 市盈率, 市净率\n- 公司主要竞争对手情况\n- 指数数据: 沪深300指数日数据, 恒生指数日数据, 上证指数日数据, 纳斯达克指数日数据`}</pre></div><div><h3>原始分析任务（完整 9 项）</h3><pre>{`1. 梳理公司发展历程、关键里程碑事件及当前核心主营业务范围\n2. 分析创始团队及高管背景，梳理股权结构及主要股东情况\n3. 梳理公司上市前的融资轮次、金额及主要投资方\n4. 分析历年营收趋势、各业务板块占比变化及增长驱动因素\n5. 评估公司盈利能力（ROE、毛利率、净利率）及运营效率（各项周转率)\n6. 分析公司偿债能力（资产负债率、流动比率）及现金流结构与健康度\n7. 进行同行业竞争对手对比分析，评估行业地位及核心竞争力（技术/品牌/渠道）\n8. 复盘近5年股价走势与成交量，分析关键事件（政策/财报/技术）对股价的影响\n9. 整理历史三大财务报表，预测未来两年核心财务数据，并进行估值分析`}</pre></div></div><p className="provenance">以上文字逐字来自官方仓库当前 `my_config.yaml`，没有翻译或重写。它是系统运行示例，不是论文完整 20 项 benchmark。</p></>}
   </div>
  </section>
  <section id="demo" className="section"><div className="sectionHead"><div><span className="kicker">INSTANCE INSPECTOR</span><h2>一条数据，拆开来看</h2></div><p>交互查看不同评测范式的数据形态。rubric 采用“可独立判断 + 明确权重”的结构，便于人评与自动 judge 对齐。</p></div><div className="inspector"><div className="demoList">{benchmarks.map(b=><button key={b.id} className={`demoButton ${active.id===b.id?"active":""}`} onClick={()=>setSelected(b.id)}><b>{b.name}</b><span>{b.demo.task}</span></button>)}</div><div className="demoBody"><div className="demoMeta"><span>{active.scope}</span><span>{active.demo.task}</span><span>{active.access}</span></div><div className="demoGrid"><div className="demoPanel"><h4>Input / Context</h4><p>{active.demo.input}</p></div><div className="demoPanel"><h4>Expected Deliverable</h4><p>{active.demo.output}</p></div><div className="demoPanel rubric"><h4>Scoring Rubric</h4>{active.demo.rubric.map((r,i)=><div className="rubricRow" key={r.text}><span>R{i+1}</span><span>{r.text}</span><span className="points">+{r.points} pts</span></div>)}</div></div><p className="note">样例用于说明 schema 与可视化方式；请从“公开数据”链接获取原始条目并遵守其许可证。仓库 data/benchmarks.json 是页面的唯一内容源。</p></div></div></section>
  <footer className="footer"><span>FinEval Atlas · An open research map for financial evaluation design</span><span>数据层 → data/benchmarks.json · 内容更新 2026-08-25</span></footer>
 </main>
}
