"use client";
import { useMemo, useState } from "react";

type Rubric={text:string;points:number}; type Demo={title:string;task:string;input:string;output:string;rubric:Rubric[]};
type Benchmark={id:string;name:string;year:string;scope:string;summary:string;tasks:string[];expert:string;rubric:string;access:string;paper:string;data:string;demo:Demo};
type FinSearchRow={prompt_id:string;prompt:string;response_reference?:string|null;judge_prompt_template?:string|null;judge_system_prompt?:string|null;label:string;[key:string]:unknown};

const groups=["ȫ��","�����о�","�ĵ��ʴ�","��ֵ����","�����ɹ�","����������","��ģ̬","��������","�������","��ȫ�Ϲ�"];
const matrixTasks=["�ĵ��ʴ�","��ֵ����","�����о�","�����ɹ�","���ߵ���","���ֽ���","��ģ̬","��������","�������","��ȫ�Ϲ�"];

export default function Explorer({benchmarks,finsearchRaw}:{benchmarks:Benchmark[];finsearchRaw:FinSearchRow[]}){
 const [group,setGroup]=useState("ȫ��"); const [query,setQuery]=useState(""); const [selected,setSelected]=useState(benchmarks[0].id);
 const [finRegion,setFinRegion]=useState("Greater China"); const [finTier,setFinTier]=useState("T1"); const [finIndex,setFinIndex]=useState(0);
 const [sightTab,setSightTab]=useState("dataset");
 const filtered=useMemo(()=>benchmarks.filter(b=>(group==="ȫ��"||b.tasks.includes(group))&&(b.name+b.summary+b.tasks.join("")).toLowerCase().includes(query.toLowerCase())),[benchmarks,group,query]);
 const active=benchmarks.find(b=>b.id===selected) || benchmarks[0];
 const finRows=useMemo(()=>finsearchRaw.filter(r=>r.label.includes(`(${finRegion})`)&&r.prompt_id.startsWith(`(${finTier})`)),[finsearchRaw,finRegion,finTier]);
 const finRow=finRows[Math.min(finIndex,Math.max(0,finRows.length-1))];
 const setFinFilter=(kind:"region"|"tier",value:string)=>{if(kind==="region")setFinRegion(value);else setFinTier(value);setFinIndex(0)};
 return <main className="shell">
  <nav className="nav"><div className="brand">FinEval <i>Atlas</i></div><div className="navlinks"><a href="/general">ͨ�� Agent Bench</a><a href="#landscape">���ݼ�</a><a href="#tasks">����ͼ��</a><a href="#demo">Demo</a><a className="github" href="https://github.com/yuedai-pbc/FinEval-Atlas" target="_blank" rel="noreferrer">Repository �J</a></div></nav>
  <header className="hero"><div><span className="eyebrow">Financial Evaluation Intelligence �� v0.1</span><h1>�ѽ������⼯<br/>��<span className="highlight">��ִ��</span>�Ŀ�����</h1><p className="lede">��ֹ�ռ����ġ����ǰ�����������ר�����������ֹ������ͬһ��ͼ��������о��߿��ٻش𣺲�ʲô����ô���졢˭���жϣ��Լ�һ�����ݾ�����ε÷֡�</p></div><aside className="heroAside"><strong>{benchmarks.length}</strong><p>��������������<br/>�����ṹ������</p><strong>{new Set(benchmarks.flatMap(b=>b.tasks)).size}</strong><p>����������<br/>���ʴ���ʵ�����ɹ�</p></aside></header>
  <section className="section"><div className="sectionHead"><div><span className="kicker">DESIGN BLUEPRINT</span><h2>һ��������������ε���</h2></div><p>ר�Ҳ������ա�����֡��ų��֣����ǹᴩ�����塢���������rubric ��д��ä���������ٲá�</p></div><div className="pipeline">{[["01","�������","����ʵ���ڹ��������λ�ɹ��ﷴ������"],["02","ר��׫д","��ҵ���ṩ��ʾ�������ġ�������ο���"],["03","�������","��һλר�Ҽ����ʵ�ԡ��ɽ���������"],["04","Rubric ԭ�ӻ�","����ȷ�Բ�ɿɶ�����֤����Ȩ�ص����ֵ�"],["05","ä��У׼","����ä�� + judge У׼����¼���������Ŷ�"]].map(x=><div className="stage" key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
  <section id="landscape" className="section"><div className="sectionHead"><div><span className="kicker">BENCHMARK LANDSCAPE</span><h2>���������ݼ�</h2></div><p>�����š����ֹ����������빫���Ӽ������� Demo ��Ϊ�ṹʾ�����ڹ����ֶεĽ�ѡ�������ԭʼ�������ɡ�</p></div><div className="controls">{groups.map(g=><button key={g} className={`chip ${group===g?"active":""}`} onClick={()=>setGroup(g)}>{g}</button>)}<input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="�������ݼ� / ����..." aria-label="����"/></div><div className="cards">{filtered.length?filtered.map(b=><article className="card" key={b.id}><div className="cardTop"><span className="eyebrow">{b.year} �� {b.scope}</span><span className={`status ${b.access.includes("�Ӽ�")?"partial":""}`}>{b.access}</span></div><h3>{b.name}</h3><p className="summary">{b.summary}</p><div className="tags">{b.tasks.map(t=><span className="tag" key={t}>{t}</span>)}</div><div className="facts"><div><small>ר�Ҳ���</small><b>{b.expert}</b></div><div><small>���ַ�ʽ</small><b>{b.rubric}</b></div></div><div className="links"><a href={b.paper} target="_blank">���� / ˵�� �J</a><a href={b.data} target="_blank">�������� �J</a><a href="#demo" onClick={()=>setSelected(b.id)}>�鿴 Demo ��</a></div></article>):<div className="empty">û��ƥ���������Ը������Ĺؼ��ʡ�</div>}</div></section>
  <section id="tasks" className="section"><div className="sectionHead"><div><span className="kicker">TASK COVERAGE</span><h2>���񸲸Ǿ���</h2></div><p>Բ���ʾ��������ɺ��ɫ��ʾ��Ӹ��ǡ�����ʾ��ͳ�ʴ�����ʵ����������֮��Ķϲ㡣</p></div><div className="matrixWrap"><table className="matrix"><thead><tr><th>���⼯</th>{matrixTasks.map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{benchmarks.map(b=><tr key={b.id}><td>{b.name}</td>{matrixTasks.map(t=><td key={t}>{b.tasks.includes(t)?<span className="dot"/>:(t==="��ȫ�Ϲ�"&&b.tasks.includes("����������"))?<span className="dot half"/>:<span className="dash">��</span>}</td>)}</tr>)}</tbody></table></div></section>
  <section id="finsearch-raw" className="section"><div className="sectionHead"><div><span className="kicker">OFFICIAL DATASET �� UNEDITED</span><h2>FinSearchComp ԭʼ���Լ�</h2></div><p>���� 635 ����¼ֱ�����Թٷ� CC BY 4.0 �����ļ������⡢��׼�𰸡���ǩ�� judge prompt ��δ���롢��д���ܽᡣ</p></div>
   <div className="sourceRail"><a href="https://proceedings.iclr.cc/paper_files/paper/2026/hash/4d42358702dff82e1436550a05ade260-Abstract-Conference.html" target="_blank">ICLR 2026 ���� �J</a><a href="https://arxiv.org/abs/2509.13160" target="_blank">arXiv �J</a><a href="https://randomtutu.github.io/FinSearchComp/" target="_blank">��Ŀ��ҳ �J</a><a href="https://github.com/randomtutu/FinSearchComp" target="_blank">�ٷ� GitHub �J</a><a href="https://huggingface.co/datasets/ByteSeedXpert/FinSearchComp" target="_blank">Hugging Face �J</a><a href="https://huggingface.co/datasets/ByteSeedXpert/FinSearchComp/blob/main/finsearchcomp_data.json" target="_blank">ԭʼ JSON �J</a><a href="https://github.com/randomtutu/FinSearchComp/tree/main/finsearchcomp/eval" target="_blank">������� �J</a></div>
   <div className="finSummary"><div><strong>635</strong><span>ԭʼ����</span></div><div><strong>2</strong><span>�����Ӽ�</span></div><div><strong>3</strong><span>����㼶</span></div><div><strong>70</strong><span>����ר��</span></div></div>
   <div className="coverageGrid"><div className="coverageTitle">ԭʼ��¼�ֲ�</div>{[["Greater China","T1",110],["Greater China","T2",100],["Greater China","T3",88],["Global","T1",134],["Global","T2",119],["Global","T3",84]].map(([r,t,n])=><button key={`${r}${t}`} className={`coverageCell ${finRegion===r&&finTier===t?"active":""}`} onClick={()=>{setFinRegion(String(r));setFinTier(String(t));setFinIndex(0)}}><span>{r}</span><b>{t}</b><i style={{width:`${Number(n)/1.34}%`}}/><em>{n} ��</em></button>)}</div>
   <div className="rawExplorer"><aside className="rawFilters"><label>���� / Market</label>{["Greater China","Global"].map(r=><button key={r} className={finRegion===r?"active":""} onClick={()=>setFinFilter("region",r)}>{r}<small>{r==="Greater China"?"���л��г�":"ȫ���г�"}</small></button>)}<label>���� / Task</label>{[["T1","Time-Sensitive Data Fetching"],["T2","Simple Historical Lookup"],["T3","Complex Historical Investigation"]].map(([t,n])=><button key={t} className={finTier===t?"active":""} onClick={()=>setFinFilter("tier",t)}>{t}<small>{n}</small></button>)}</aside>
    <div className="rawRecord">{finRow&&<><div className="recordNav"><div><span>OFFICIAL RECORD</span><b>{finRow.prompt_id}</b></div><div className="pager"><button disabled={finIndex===0} onClick={()=>setFinIndex(i=>i-1)}>��</button><span>{finIndex+1} / {finRows.length}</span><button disabled={finIndex===finRows.length-1} onClick={()=>setFinIndex(i=>i+1)}>��</button></div></div><div className="rawField primary"><label>prompt</label><p>{finRow.prompt}</p></div><div className="rawField answer"><label>response_reference</label><p>{finRow.response_reference || <i>�ٷ���¼Ϊ�գ�T1 ��ʵʱ API / ground truth ����̬��֤</i>}</p></div><div className="rawField"><label>label</label><p>{finRow.label}</p></div><details className="rawDetails"><summary>չ���ٷ� Judge �ֶ���ȫ��ԭʼ�ֶ�</summary><div className="rawField"><label>judge_prompt_template</label><pre>{finRow.judge_prompt_template || "null"}</pre></div><div className="rawField"><label>judge_system_prompt</label><pre>{finRow.judge_system_prompt || "null"}</pre></div><div className="rawField"><label>raw JSON object</label><pre>{JSON.stringify(finRow,null,2)}</pre></div></details></>}</div>
   </div><p className="provenance">��Դ�汾��randomtutu/FinSearchComp main �� data/finsearchcomp_data.json �� SHA ff89538172a93e10e85f04ca666bbf5adba2df6d �� ҳ����ı��Ű棬���ı��ֶ����ݡ�</p>
  </section>
  <section id="finsight-audit" className="section"><div className="sectionHead"><div><span className="kicker">PAPER �� CODE AUDIT</span><h2>FinSight�����⼯�뿪Դ����</h2></div><p>���ƺ˶ԣ�δ��������Ӧ�� ��FirmSight�� �������ģ��˴�����ǰ�� ACL 2026 FinSight���������Ƶ� benchmark ��ֿ�ʵ�ʿ������ݷֿ�չʾ��</p></div>
   <div className="sourceRail"><a href="https://aclanthology.org/2026.acl-long.265/" target="_blank">ACL Anthology �J</a><a href="https://aclanthology.org/2026.acl-long.265.pdf" target="_blank">��ʽ PDF �J</a><a href="https://arxiv.org/abs/2510.16844" target="_blank">arXiv �J</a><a href="https://github.com/RUC-NLPIR/FinSight" target="_blank">�ٷ� GitHub �J</a><a href="https://github.com/RUC-NLPIR/FinSight/blob/main/README.md" target="_blank">README �J</a><a href="https://github.com/RUC-NLPIR/FinSight/tree/main/assets/example_reports" target="_blank">���ɱ������� �J</a><a href="https://github.com/RUC-NLPIR/FinSight/blob/main/my_config.yaml" target="_blank">�ٷ�����ʵ�� �J</a><a href="https://github.com/RUC-NLPIR/FinSight/tree/main/src/agents" target="_blank">Agent Դ�� �J</a><a href="https://github.com/RUC-NLPIR/FinSight/tree/main/src/tools" target="_blank">���߿� �J</a></div>
   <div className="auditAlert"><b>�����Խ���</b><span>����ϵͳ���룺�ѿ���</span><span>20 ������Ŀ���嵥��δ�ڲֿ��ҵ�</span><span>ȯ�̽�걨�棺δ�ڲֿ��ҵ�</span><span>��������ű���δ�ڲֿ��ҵ�</span></div>
   <div className="sightTabs">{[["dataset","01 ���⼯"],["metrics","02 ָ����ר��"],["code","03 �������"],["original","04 �ٷ�ԭʼʵ��"]].map(([id,n])=><button key={id} className={sightTab===id?"active":""} onClick={()=>setSightTab(id)}>{n}</button>)}</div>
   <div className="sightPanel">{sightTab==="dataset"&&<><div className="sightHero"><div><strong>20</strong><span>����Ŀ��</span></div><div><strong>10</strong><span>��˾��</span></div><div><strong>10</strong><span>��ҵ��</span></div><div><strong>&gt;20</strong><span>��걨��ҳ���ż�</span></div><div><strong>&gt;20</strong><span>ͼ�������ż�</span></div></div><div className="twoCols"><div className="infoBlock"><span className="blockNo">A</span><h3>Company-level</h3><p>������������Ȩ������ƽ̨ѡ��ͬ�г�����ҵ����ֵ�Ĺ�˾������ A �ɡ��۹ɵȡ�ÿ��Ŀ����һ��רҵȯ����ȱ�����Ϊ golden reference��</p><b>����״̬</b><p className="warning">���� 10 �ҹ�˾�����Ͷ�Ӧ��걨��Ŀǰδ�ڹٷ��ֿⷢ�������ĸ�¼ֻչʾ�����Ƽ�������</p></div><div className="infoBlock"><span className="blockNo">B</span><h3>Industry-level</h3><p>����������ѡ�����ƽ̨�ϵĸ߹�ע��ҵ��Ϊ�о�Ŀ�꣬ʹ��רҵ������ҵ������Ϊ golden reference��</p><b>����״̬</b><p className="warning">���� 10 ����ҵ�����Ͷ�Ӧ��걨��Ŀǰδ�ڹٷ��ֿⷢ�����ֿ⹫���ˡ����� AI Agent ��չ�����ɱ���������</p></div></div><div className="flowline"><span>Research target</span><i>��</i><span>רҵȯ�̽�걨��</span><i>��</i><span>ģ�����ɳ�����</span><i>��</i><span>9 �� 0�C10 ������</span></div></>}
    {sightTab==="metrics"&&<><div className="metricGrid">{[["Factual Accuracy","Core Conclusion Consistency","Textual Faithfulness","Text�CImage Coherence"],["Information Effectiveness","Information Richness","Coverage","Analytical Insight"],["Presentation Quality","Structural Logic","Language Professionalism","Chart Expressiveness"]].map((m,i)=><div className="metricGroup" key={m[0]}><span>0{i+1}</span><h3>{m[0]}</h3>{m.slice(1).map(x=><p key={x}>{x}</p>)}</div>)}</div><div className="judgeGrid"><div><b>�Զ�����</b><p>Gemini-2.5-Pro Ϊ�� judge��ÿ�������������� 3 �β����� 95% �������䣻GPT-5 ��Ϊ���� judge ����ģ��һ���ԡ�</p></div><div><b>�˹�����</b><p>6 �����н��ڱ������о������� FinSight��Gemini-2.5-Pro Deep Research �� OpenAI Deep Research ���бȽϣ����� Krippendorff��s �� �� Pearson��s r��</p></div><div><b>����ָ��</b><p>�ؼ�������ʵ�ٻأ�FinSight ƽ������ 7.1/13���ٻ��� 54.6%��������������ԴȨ���Էֲ���</p></div></div><div className="scoreTable"><div className="scoreHead"><span>ϵͳ</span><span>Fact.</span><span>Analytical</span><span>Presentation</span><span>Avg.</span></div>{[["FinSight","7.40*","8.48*","8.05*","8.09"],["Gemini-2.5-Pro DR","6.18*","7.68*","6.58*","6.82"],["OpenAI DR","5.98*","6.22*","6.80*","6.11"]].map(r=><div className="scoreRow" key={r[0]}>{r.map((x,i)=><span key={i}>{x}</span>)}</div>)}</div><p className="provenance">* ����ά��ֵΪ���ı����и��� 3 ����ָ���ҳ��չʾ�Ծ�ֵ����ʽ�Ƚ�Ӧ�����ľ���ԭʼ����Ϊ׼��</p></>}
    {sightTab==="code"&&<><div className="codeMatrix">{[["�� Agent ������","�ѿ���","src/agents"],["�������۹��߿�","�ѿ���","src/tools"],["CAVM / Memory","�ѿ���","src/memory"],["Prompt ģ��","�ѿ���","src/agents/*/prompts"],["Web UI","�ѿ���","demo/frontend + backend"],["���ɱ�������","���ֿ���","assets/example_reports"],["20 �� benchmark ����","δ����","�ֿ�δ����"],["ȯ�� golden reports","δ����","�ֿ�δ����"],["���� 9 ָ���������","δ����","�ֿ�δ����"]].map(r=><div className="codeRow" key={r[0]}><b>{r[0]}</b><span className={r[1]==="δ����"?"closed":r[1]==="���ֿ���"?"partial":"open"}>{r[1]}</span><code>{r[2]}</code></div>)}</div><div className="architectureStrip">{["Data Collector","Deep Search Agent","Data Analyzer + VLM","Report Generator","DOCX / PDF"].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b></div>)}</div><p className="auditNote">��������֤�Բֿ⵱ǰ LICENSE/README Ϊ׼����ǰ README ��ʾ GPL v3����������Ҫ LLM��VLM��Embedding ���ѡ���� API����ˡ����뿪�š����������Ľ������ɱ����֡�</p></>}
    {sightTab==="original"&&<><div className="originalHead"><div><span>OFFICIAL FILE</span><b>my_config.yaml</b></div><a href="https://github.com/RUC-NLPIR/FinSight/blob/main/my_config.yaml" target="_blank">�� GitHub ���� �J</a></div><div className="configColumns"><div><h3>ԭʼ�о�Ŀ��</h3><pre>{`target_name: "�����Ƽ�"\nstock_code: "00020.hk"\ntarget_type: 'financial_company'\noutput_dir: "./outputs/exp-v3"\nlanguage: 'zh'`}</pre><h3>ԭʼ���ݲɼ�����</h3><pre>{`- �ʲ���ծ��, �����, �ֽ�������������񱨱�\n- ��Ʊ������Ϣ�Լ��ɼ�����\n- �ɶ��ṹ\n- Ͷ������\n- ��˾������, ���ʲ�������(ROE), ��ӯ��, �о���\n- ��˾��Ҫ�����������\n- ָ������: ����300ָ��������, ����ָ��������, ��ָ֤��������, ��˹���ָ��������`}</pre></div><div><h3>ԭʼ������������ 9 �</h3><pre>{`1. ������˾��չ���̡��ؼ���̱��¼�����ǰ������Ӫҵ��Χ\n2. ������ʼ�ŶӼ��߹ܱ�����������Ȩ�ṹ����Ҫ�ɶ����\n3. ������˾����ǰ�������ִΡ�����ҪͶ�ʷ�\n4. ��������Ӫ�����ơ���ҵ����ռ�ȱ仯��������������\n5. ������˾ӯ��������ROE��ë���ʡ������ʣ�����ӪЧ�ʣ�������ת��)\n6. ������˾��ծ�������ʲ���ծ�ʡ��������ʣ����ֽ����ṹ�뽡����\n7. ����ͬ��ҵ�������ֶԱȷ�����������ҵ��λ�����ľ�����������/Ʒ��/������\n8. ���̽�5��ɼ�������ɽ����������ؼ��¼�������/�Ʊ�/�������Թɼ۵�Ӱ��\n9. ������ʷ������񱨱���Ԥ��δ��������Ĳ������ݣ������й�ֵ����`}</pre></div></div><p className="provenance">���������������Թٷ��ֿ⵱ǰ `my_config.yaml`��û�з������д������ϵͳ����ʾ���������������� 20 �� benchmark��</p></>}
   </div>
  </section>
  <section id="demo" className="section"><div className="sectionHead"><div><span className="kicker">INSTANCE INSPECTOR</span><h2>һ�����ݣ�������</h2></div><p>�����鿴��ͬ���ⷶʽ��������̬��rubric ���á��ɶ����ж� + ��ȷȨ�ء��Ľṹ�������������Զ� judge ���롣</p></div><div className="inspector"><div className="demoList">{benchmarks.map(b=><button key={b.id} className={`demoButton ${active.id===b.id?"active":""}`} onClick={()=>setSelected(b.id)}><b>{b.name}</b><span>{b.demo.task}</span></button>)}</div><div className="demoBody"><div className="demoMeta"><span>{active.scope}</span><span>{active.demo.task}</span><span>{active.access}</span></div><div className="demoGrid"><div className="demoPanel"><h4>Input / Context</h4><p>{active.demo.input}</p></div><div className="demoPanel"><h4>Expected Deliverable</h4><p>{active.demo.output}</p></div><div className="demoPanel rubric"><h4>Scoring Rubric</h4>{active.demo.rubric.map((r,i)=><div className="rubricRow" key={r.text}><span>R{i+1}</span><span>{r.text}</span><span className="points">+{r.points} pts</span></div>)}</div></div><p className="note">��������˵�� schema ����ӻ���ʽ����ӡ��������ݡ����ӻ�ȡԭʼ��Ŀ������������֤���ֿ� data/benchmarks.json ��ҳ���Ψһ����Դ��</p></div></div></section>
  <footer className="footer"><span>FinEval Atlas �� An open research map for financial evaluation design</span><span>���ݲ� �� data/benchmarks.json �� ���ݸ��� 2026-08-25</span></footer>
 </main>
}

