"use client";
import {useState} from "react";
import "./finchain.css";

const domains=[
 ["Accounting & Financial Reporting",4],["Corporate Finance",5],["Crypto Finance",7],["Finance Regulation",5],
 ["Financial Markets",4],["Financial Ratios",4],["Fintech",3],["Investment Analysis",5],
 ["Mergers & Acquisitions",5],["Personal Finance",5],["Risk Management",7],["Sustainable Finance",5]
] as const;

export default function FinChainSection(){
 const [tab,setTab]=useState("dataset");
 return <section id="finchain-audit" className="section">
  <div className="sectionHead"><div><span className="kicker">OFFICIAL TEMPLATE × APPENDIX AUDIT</span><h2>FinChain：从模板到逐步评分</h2></div><p>页面直接对应 ACL 2026 正式论文与官方仓库。原始开放对象主要是 58 个 Python 主题文件和 ChainEval 代码，而不是一个静态、不可变的 JSON 测试表。</p></div>
  <div className="sourceRail"><a href="https://aclanthology.org/2026.acl-long.662/" target="_blank">ACL 2026 论文 ↗</a><a href="https://aclanthology.org/2026.acl-long.662.pdf" target="_blank">正式 PDF ↗</a><a href="https://arxiv.org/abs/2506.02515" target="_blank">arXiv ↗</a><a href="https://github.com/mbzuai-nlp/finchain" target="_blank">官方 GitHub ↗</a><a href="https://mbzuai-nlp.github.io/finchain/" target="_blank">项目主页 ↗</a><a href="https://mbzuai-nlp.github.io/finchain/leaderboard.html" target="_blank">Leaderboard ↗</a><a href="https://huggingface.co/spaces/Usmansafder/finchain-space" target="_blank">交互 Demo ↗</a><a href="https://github.com/mbzuai-nlp/finchain/tree/main/data/templates" target="_blank">原始模板 ↗</a><a href="https://github.com/mbzuai-nlp/finchain/tree/main/chaineval" target="_blank">评测代码 ↗</a></div>
  <div className="auditAlert"><b>开放性结论</b><span>290 个生成模板：开放</span><span>ChainEval：开放</span><span>固定生成后的 2,900 条 JSONL：仓库未附带</span><span>随机 seed 使实例可再生成</span></div>
  <div className="sightTabs">{[["dataset","01 数据集"],["sample","02 原始样例"],["experts","03 专家与质检"],["rubric","04 ChainEval / Rubric"],["paper","05 论文导读"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
  <div className="sightPanel">
   {tab==="dataset"&&<><div className="sightHero"><div><strong>12</strong><span>金融领域</span></div><div><strong>58</strong><span>金融主题</span></div><div><strong>290</strong><span>Python 模板</span></div><div><strong>10×</strong><span>每模板 seeds</span></div><div><strong>2,900</strong><span>可生成实例</span></div></div><div className="domainGrid">{domains.map(([d,n])=><div key={d}><b>{d}</b><span>{n} topics</span><i style={{width:`${n/7*100}%`}}/></div>)}</div><div className="difficultyRow"><div><b>Basic</b><strong>116 templates</strong><span>平均 2.01 步；每主题 2 个模板</span></div><div><b>Intermediate</b><strong>116 templates</strong><span>平均 2.97 步；每主题 2 个模板</span></div><div><b>Advanced</b><strong>58 templates</strong><span>平均 3.90 步；每主题 1 个模板</span></div></div><p className="auditNote">论文称数据集为 2,900 个实例；仓库当前开放的是生成这些实例的模板代码。每次运行模板会随机产生 seed 和参数，因此页面不把自行生成的一条记录冒充为论文唯一固定测试条目。</p></>}
   {tab==="sample"&&<><div className="originalHead"><div><span>OFFICIAL TEMPLATE REPLAY</span><b>investment_analysis/npv.py · seed 20260825</b></div><a href="https://github.com/mbzuai-nlp/finchain/blob/main/data/templates/investment_analysis/npv.py" target="_blank">核对源代码 ↗</a></div><div className="chainSample"><div><h3>生成后的原始 question</h3><pre>John Doe can invest $84004 in Google Data Center Build. The project will save $17525 per year for 4 years, after which it can be sold for $58041 but will incur an environmental cleanup cost of $17490. Given a discount rate of 8.36%, what is the NPV?</pre><div className="schemaStrip"><code>seed</code><span>20260825</span><code>id</code><span>5</span><code>level</code><span>Advanced</span></div></div><div><h3>生成后的原始 solution</h3><pre>{`Step 1 – PV of the annual savings (annuity):\n  PV_annuity = $17525 × [(1 − 1/(1+0.0836)^4)/(0.0836)] = $57,582.92\n\nStep 2 – PV of the salvage value:\n  PV_salvage = $58041/(1+0.0836)^4 = $42,097.75\n\nStep 3 – PV of the cleanup cost:\n  PV_cleanup = $17490/(1+0.0836)^4 = $12,685.68\n\nStep 4 – Net present value:\n  NPV = $57,582.92 + $42,097.75 − $12,685.68 − $84004 = $2,990.99`}</pre></div></div><p className="provenance">这是用官方模板函数和固定随机 seed 直接生成的展示记录；文字与数值未经总结或改写。仓库 main 分支自身没有提交生成后的 testset JSONL。</p></>}
   {tab==="experts"&&<><div className="expertFlow"><div><strong>10</strong><b>金融专家</b><span>7 名经济/金融/量化方向研究生 + 3 名量化研究、金融工程、风险管理从业者</span></div><div><strong>20</strong><b>共同校准模板</b><span>所有标注者先完成 pilot，共同讨论并对齐判定标准</span></div><div><strong>270</strong><b>独立分配模板</b><span>随机分配，每个剩余模板由 1 位专家审核</span></div><div><strong>29</strong><b>发现并返修</b><span>占 290 个模板的 10%，由金融专家修订</span></div></div><div className="issueBars">{[["Representation Error",12,"41.4%"],["Clarity Issue",9,"31.0%"],["Formula Choice Error",5,"17.2%"],["Math / Logic Error",3,"10.3%"],["Robustness Error",2,"6.9%"]].map(([x,n,p])=><div key={x}><b>{x}</b><i style={{width:`${Number(n)/12*100}%`}}/><span>{n} · {p}</span></div>)}</div><p className="auditNote">模板审核是二元 verdict：Correct / Incorrect。Incorrect 必须选择至少一个问题标签、提交最小代码修复并说明理由。问题标签可重叠，因此各类计数之和大于 29。</p></>}
   {tab==="rubric"&&<><div className="metricGrid"><div className="metricGroup"><span>01</span><h3>Step alignment</h3><p>按顺序切分 gold 与 prediction 的推理步骤</p><p>句向量语义相似度 + 数值一致性 gate</p><p>用 Dynamic Time Warping 允许插入、遗漏与压缩</p></div><div className="metricGroup"><span>02</span><h3>Final Answer</h3><p>FAC 检查最终结果</p><p>数值答案采用 ε = 0.05 相对容差</p><p>非数值答案检查一致性</p></div><div className="metricGroup"><span>03</span><h3>ChainEval</h3><p>ChainEval = 0.9 × DTWGate + 0.1 × FAC</p><p>输出范围 [0,1]，越高越好</p><p>权重由人评相关性网格搜索确定</p></div></div><div className="twoCols"><div className="infoBlock"><h3>人评量表 A：Reasoning Process Quality</h3><p>1 Unacceptable · 2 Poor · 3 Fair · 4 Good · 5 Excellent。检查逻辑连贯性、事实正确性、步骤完整性以及是否符合有效金融原则。</p></div><div className="infoBlock"><h3>人评量表 B：Final Answer Accuracy</h3><p>同样采用 1–5 分，对照问题、标准参考答案和匿名模型回答，判断最终结论的正确性、完整性与支持程度。</p></div></div><p className="provenance">ChainEval 的受控验证抽取 20 个问题 × 5 个模型，共 100 个匿名回答，由金融专家独立评分；论文报告推理质量与最终答案人评分的 Spearman ρ &gt; 0.94。</p></>}
   {tab==="paper"&&<><div className="paperBrief"><div><span>VENUE</span><h3>ACL 2026 · Main Conference</h3><p>正式版本：ACL Anthology 2026.acl-long.662。</p></div><div><span>摘要导读</span><p>论文认为，FinQA 等金融推理基准主要验证最终数值，难以判断模型是否通过正确过程得到答案。FinChain 用可执行的参数化模板提供逐步金标，再用 ChainEval 同时检查步骤语义、步骤数值和最终结果。</p></div><div><span>主要卖点</span><p>从零构造、可扩展生成、可执行验证、污染风险更低；难度由推理步骤数与组合复杂度控制；能够定位模型究竟是漏步骤、算错数字，还是仅碰巧得到正确最终答案。</p></div></div><div className="chapterGrid"><div><b>§3 Dataset</b><p>12 领域 → 58 主题 → 每主题 5 个模板 → 每模板 10 个 seeds。</p></div><div><b>§4 ChainEval</b><p>语义—数值 gating、DTW 顺序对齐、FAC 与最终加权。</p></div><div><b>§5 Experiments</b><p>26 个模型、四类模型族；前沿模型领先，但高级组合推理仍明显下降。</p></div><div><b>Appendix A–B</b><p>模板生成 prompt、验证约束、10 位专家协议、错误分布和 1–5 分人评 rubric。</p></div><div><b>Appendix C–F</b><p>模型配置、指标消融与人评相关性、领域/难度结果、错误类型分析。</p></div></div></>}
  </div>
 </section>
}
